import type { RoleGuide } from './types';
import { askAgentTopic, notificationsTopic, accessTip, signInTopic } from './shared';

export const adminGuide: RoleGuide = {
  slug: 'admin',
  hubTitle: 'Admin Hub',
  hubDesc: 'Centralized help for managing your EduOS operations.',
  heroText: 'Manage your school operations, users, classes, finances, and more from one place.',
  quickActions: ['users', 'student-classes', 'payments', 'document-requests', 'tickets', 'announcements'],
  help: {
    title: 'Need advanced support?',
    text: 'Check the audit logs or update your school settings if you\'re stuck.',
    label: 'Open Settings',
    href: '/admin/settings',
  },
  topics: [
    {
      id: 'dashboard', title: 'Your Admin dashboard', category: 'Home Base', icon: '◫',
      href: '/admin', openLabel: 'Open Dashboard',
      summary: 'The Dashboard gives you a complete overview of your school\'s daily operations.',
      highlights: [
        { label: 'Open Tickets', text: 'Support requests that still need an answer, with a link to view them all.' },
        { label: 'Admissions Pipeline', text: 'How many prospective families are at each stage, with a shortcut to the CRM.' },
        { label: 'Recent Announcements', text: 'The latest notices published to the school.' },
        { label: 'Recently Added Students', text: 'New students with their admission numbers.' },
      ],
    },
    {
      id: 'tickets', title: 'Keep issues moving.', category: 'Home Base', icon: '✉',
      href: '/admin/tickets', openLabel: 'Open Tickets',
      summary: 'Read and answer support requests from students, parents and staff, and raise new ones.',
      workflow: ['Open ticket', 'Read the conversation', 'Type a reply', 'Send'],
      steps: [
        'Open a ticket to see the full conversation, who it is regarding and its status (New, Open, Waiting, Resolved or Closed).',
        'Type a reply and press Send.',
        'To raise a ticket yourself, click "+ New ticket", enter the subject and message, and choose who it goes to under "Route to": class teacher, admin office, warden, librarian or principal.',
      ],
      tips: ['Messages that arrived over WhatsApp are marked "via WhatsApp".'],
    },
    {
      id: 'users', title: 'Manage your users', category: 'People', icon: '◉',
      href: '/admin/users', openLabel: 'Open User Management',
      summary: 'Accounts are phone-rooted and can hold one or more role profiles. Add students, teachers, parents and staff here.',
      workflow: ['Click Add User', 'Select Role', 'Enter details', 'Save'],
      steps: [
        'Search by name, phone or email, and filter the list by role or class.',
        'Click Add User, pick the role, and enter the full name and phone (E.164 format, e.g. +919555000111).',
        'Optionally add an email and password (minimum 6 characters) for email sign-in, an admission number, and a class/section for students.',
        'To create many accounts at once, use Bulk Upload with the CSV template. Student rows can include gradeName and sectionName to assign a class immediately.',
      ],
      tips: ['Grade names like "Grade 5", "Std 5" or "5" all match a grade stored as "Class 5" during bulk upload.'],
    },
    {
      id: 'student-classes', title: 'Keep classes organized.', category: 'People', icon: '◑',
      href: '/admin/student-classes', openLabel: 'Open Student Classes',
      summary: 'See every student and their current class enrollment, and place students into sections.',
      steps: [
        'Search by name, admission number or class. Students without a class show "Awaiting class assignment".',
        'Click Assign Section, choose the section and academic year. The roll number is filled in automatically, and you can change it.',
        'Use "+ Add Student" to create a student record directly, or "⇧ Bulk assign" to enroll many admission numbers into one section with a CSV.',
      ],
    },
    {
      id: 'teacher-classes', title: 'See who teaches each class', category: 'People', icon: '◐',
      href: '/admin/teacher-classes', openLabel: 'Open Teacher Classes',
      summary: 'Pick a grade and section to see its class teacher and every subject with its teacher.',
      steps: [
        'Choose a Grade, then a Section.',
        'Review the class teacher and the subject list. "Unassigned" means no teacher yet.',
        'To change assignments, use Classroom Mgmt → Subject Offerings.',
      ],
    },
    {
      id: 'admissions', title: 'Track admissions in the CRM', category: 'People', icon: '◌',
      href: '/admin/admissions', openLabel: 'Open Admission CRM',
      summary: 'Follow prospective families through each stage, from first enquiry to enrollment.',
      workflow: ['New lead', 'Follow up', 'Move stage', 'Enrolled'],
      steps: [
        'Add a lead with the child\'s name, guardian, contact details, grade applying for and source (Web, Referral…).',
        'Open a lead to call or email the family, set the next action and date, and note what was discussed.',
        'Use "Move stage" as the family progresses. When a lead is enrolled, the student is added to the Student List.',
        'Import many leads at once with "⇧ Bulk upload". They start in the NEW stage.',
      ],
    },
    {
      id: 'medical', title: 'Student medical records', category: 'People', icon: '✚',
      href: '/admin/medical', openLabel: 'Open Medical Records',
      summary: 'Create, update or remove any student\'s health record.',
      steps: [
        'Choose a class/section, then a student.',
        'Fill in basic info (blood group, height, weight), emergency contact, allergies and regular medications. Separate multiple entries with commas.',
        'Upload reports or files and add medical history, then save.',
      ],
      tips: ['Medical details are stored encrypted and are only visible to roles with medical permission.'],
    },
    {
      id: 'classrooms', title: 'Set up grades, sections and subjects', category: 'Academic Ops', icon: '▦',
      href: '/admin/classrooms', openLabel: 'Open Classroom Mgmt',
      summary: 'Build the academic structure every other module depends on: grades, sections, subjects and which subject is taught in which class.',
      workflow: ['Add Grade', 'Add Section', 'Add Subject', 'Assign Subject to Class'],
      steps: [
        'Grades tab: add each grade with a sort level (lower numbers appear first).',
        'Sections tab: add sections (classrooms) under a grade and set the class teacher and class representative.',
        'Subjects tab: add subjects with an optional code.',
        'Subject Offerings tab: assign a subject to a section for a term, pick the teacher, and mark it core or elective. Create a term with "+ New term" if none exists.',
      ],
      tips: ['Electives only appear to students who are approved for them, in timetables, quizzes and other lists.'],
    },
    {
      id: 'registrations', title: 'Approve elective registrations', category: 'Academic Ops', icon: '⊕',
      href: '/admin/registrations', openLabel: 'Open Subject Registrations',
      summary: 'Approve or reject students\' elective subject requests.',
      steps: [
        'Filter by Pending, Approved, Rejected or All.',
        'Approve a request, or Reject it with an optional reason that the student will see.',
      ],
    },
    {
      id: 'attendance', title: 'Check attendance across classes', category: 'Academic Ops', icon: '☱',
      href: '/admin/attendance', openLabel: 'Open Attendance',
      summary: 'View attendance for any class on any date.',
      steps: ['Choose a section and a date.', 'Review each student\'s roll number and status.'],
      tips: ['Teachers mark attendance from their own portal. Students apply for leave from theirs.'],
    },
    {
      id: 'calendar', title: 'Publish events and holidays', category: 'Academic Ops', icon: '▤',
      href: '/admin/calendar', openLabel: 'Open Calendar & Events',
      summary: 'Maintain the school-wide calendar that every portal shows.',
      steps: [
        'Add an event with a title and type: Event, Holiday, Exam or Sports.',
        'Set the start and end dates and an optional short note visible to everyone.',
      ],
    },
    {
      id: 'timetable-builder', title: 'Plan the timetable', category: 'Academic Ops', icon: '▥',
      href: '/admin/timetable', openLabel: 'Open Timetable Builder',
      summary: 'Build class-wise weekly period schedules that teachers, students and parents see.',
      steps: [
        'Pick a grade and section.',
        'Switch between Day, Week and Month views and move with ‹ Prev / Today / Next ›.',
        'Click "Add Timetable Slot" (or "+ Add slot for this day") and choose the period and subject offering.',
      ],
    },
    {
      id: 'payments', title: 'Keep finances on track.', category: 'Finance', icon: '₹',
      href: '/admin/payments', openLabel: 'Open Payments & Fees',
      summary: 'Raise invoices, record and verify payments, manage fee plans and issue receipts.',
      highlights: [
        { label: 'Invoices', text: 'Every invoice with total, paid and due date. Filter by grade, section, student or status.' },
        { label: 'Payment Receipts', text: 'Receipt numbers, amounts, method/reference and verification status.' },
        { label: 'Fee Plans', text: 'Installment plans per student and year.' },
        { label: 'Approvals', text: 'Payment changes requested by the finance team, waiting for an administrator.' },
      ],
      steps: [
        'Click "+ Create Invoice", choose the student and enrollment, and enter the description, amount and due date.',
        'Use Record on an invoice to log an offline payment (cash, cheque, demand draft or bank transfer) with its reference.',
        'Raise many invoices at once with Bulk Upload. The invoice number is generated if left blank.',
      ],
      tips: ['A student needs a class enrollment before an invoice can be raised for them.'],
    },
    {
      id: 'announcements', title: 'Broadcast important updates.', category: 'Communication', icon: '◍',
      href: '/admin/announcements', openLabel: 'Open Announcements',
      summary: 'Publish school notices and circulars.',
      workflow: ['Write', 'Choose audience', 'Preview', 'Publish'],
      steps: [
        'Write a title and the content, and optionally attach a file.',
        'Choose the audience: everyone, a class (a whole grade or one section), or a subject.',
        'Pick how to notify people (App, Email).',
        'Click Preview to see exactly who will receive it, then Publish, or go back and Edit.',
      ],
    },
    {
      id: 'library', title: 'Run the library', category: 'Communication', icon: '▢',
      href: '/admin/library', openLabel: 'Open Library Books',
      summary: 'Catalogue books, issue them to students and track returns and fines.',
      steps: [
        'Catalog tab: Add Book with title, author, category, ISBN and number of copies, or bulk upload a CSV.',
        'Click Issue on a book (or use Issue Book), choose the student and set a due date.',
        'Issued Books tab: click Return when a book comes back. Overdue books accrue fines.',
      ],
    },
    {
      id: 'transport', title: 'Bus routes and stops', category: 'Communication', icon: '⛒',
      href: '/admin/transport', openLabel: 'Open Transport Routes',
      summary: 'Manage school bus routes, stops, fares and which students ride them.',
      steps: [
        'Add Route with a name, vehicle number, driver details and an optional yearly fare.',
        'View Stops on a route to add stops in sequence with an ETA offset in minutes.',
        'Enroll Student places a student on a route and stop: pickup, drop or both.',
        'Bulk upload routes, stops or enrollments with CSV files.',
      ],
      tips: ['The fare is charged only when a student\'s transport request for that route is approved.'],
    },
    {
      id: 'transport-requests', title: 'Decide transport requests', category: 'Communication', icon: '⇄',
      href: '/admin/transport-requests', openLabel: 'Open Transport Requests',
      summary: 'Students ask for a place on a bus route. Approving grants the place and bills the fare.',
      steps: [
        'Filter by Waiting, Approved, Rejected, Withdrawn or All.',
        'Check the route, stop and fare, then Approve or Refuse.',
      ],
    },
    {
      id: 'documents', title: 'Publish documents', category: 'Communication', icon: '🗎',
      href: '/admin/documents', openLabel: 'Open Documents',
      summary: 'Publish and distribute certificates, report cards, letters and circulars.',
      steps: [
        'Click Upload Document and give it a title and type (Report Card, Transfer Certificate, Official Letter or Custom).',
        'Upload the file or paste a link.',
        'Link it to one student, or leave it unlinked to share with everyone. Choose whether parents, students or both can see it.',
      ],
    },
    {
      id: 'document-requests', title: 'Handle document requests', category: 'Communication', icon: '⇄', isNew: true,
      href: '/admin/document-requests', openLabel: 'Open Document Requests',
      summary: 'Students request certificates and letters (for example a bonafide certificate). Review each request and issue the official document.',
      workflow: ['Pending', 'Under review', 'Approved', 'Ready (issued)', 'Completed'],
      steps: [
        'Filter by student name or admission number, document type and status.',
        'Open a request to read the purpose and the student\'s answers, then click "Start review".',
        'Approve it, or Reject it with a reason the student can act on.',
        'Upload the finished document to issue it. The status becomes Ready, and Completed once the student downloads it.',
      ],
      tips: [
        'Replacing an issued file keeps the earlier version on record; the student receives the new one.',
        'A student can have only one open request per document type.',
        'Rejected or cancelled requests cannot be approved later.',
      ],
    },
    {
      id: 'document-types', title: 'Set up document types', category: 'Communication', icon: '⚙', isNew: true,
      href: '/admin/document-types', openLabel: 'Open Document Types',
      summary: 'Choose which certificates and letters students can request from the school office, and what they must tell you.',
      steps: [
        'Click "Add Suggested Types" for common documents, or "+ New type" to create your own.',
        'Give it a name, description and instructions for students.',
        'Choose which file types the office may issue and the maximum size.',
        'Add questions students answer besides the purpose (short text, long text, date, number or choice) and mark them required if needed.',
        'Turn on "Active" and "Students can request it" to make it available.',
      ],
    },
    {
      id: 'audit', title: 'Review the audit log', category: 'System', icon: '▷',
      href: '/admin/audit', openLabel: 'Open Audit Logs',
      summary: 'A complete record of administrative actions: who did what, to which record, and when.',
      steps: [
        'Filter by role, action (e.g. student.create) or month.',
        'Each entry shows the actor and their role, the target record, the channel it came through, the IP address and the time.',
      ],
    },
    {
      id: 'permissions', title: 'Control access securely.', category: 'System', icon: '🔐',
      href: '/admin/permissions', openLabel: 'Open Permissions',
      summary: 'See and adjust what each role can see and do in your school.',
      highlights: [
        { label: 'ALL', text: 'The role can act on the whole school.' },
        { label: 'OWN', text: 'The role is limited to its own classes, children or records.' },
      ],
    },
    {
      id: 'seats', title: 'Seats and buying more', category: 'System', icon: '🪑', isNew: true,
      href: '/admin/seats', openLabel: 'Open Seats',
      summary: 'See how many seats your school has bought and is using, and ask the platform for more.',
      highlights: [
        { label: 'Seats paid for / released for use', text: 'What the platform has sold and approved for your school.' },
        { label: 'In use', text: 'Active people in your school.' },
        { label: 'Available', text: 'Approved seats not yet taken.' },
      ],
      steps: [
        'Click "Request extra seats", enter the number and an optional reason (e.g. "Two new sections in Class 6").',
        'Pay for the request. It then waits for platform approval.',
        'Track the request under "Extra-seat requests" and every change under "Seat history".',
      ],
      tips: ['If no seat limit is set, nothing caps how many people your school may have.'],
    },
    {
      id: 'settings', title: 'School settings', category: 'System', icon: '⚙',
      href: '/admin/settings', openLabel: 'Open Settings',
      summary: 'Your school\'s configuration: name, branding, dropdown lists and web address.',
      highlights: [
        { label: 'School Information', text: 'Name, tenant ID, display name and logo.' },
        { label: 'Dropdown values', text: 'The lists your forms offer.' },
        { label: 'Portal address', text: 'Your subdomain or custom domain, its verification and certificate status, and the DNS records your school must create.' },
      ],
      tips: ['Branding and domains are set by the EduOS platform team. Contact them to change them.'],
    },
    askAgentTopic({
      askAbout: [
        'students, guardians and enrollments', 'attendance (including who is absent today and trends)', 'fees, invoices, payments and fee plans',
        'classes, subjects and the timetable', 'exams, marks and report cards', 'assignments and submissions', 'admission leads',
        'announcements and calendar events', 'library books, loans and requests', 'hostel rooms and residents', 'bus routes and transport requests',
        'leave, elective and student requests', 'medical records', 'tickets', 'at-risk students and dashboards', 'users and audit logs',
        'seats, and your school\'s branding and domain',
      ],
      canDo: [
        'add, enroll, update or archive students and add guardians', 'mark attendance', 'raise invoices, record, approve or reject payments, and manage fee plans and fee structures',
        'set up grades, sections, subjects and terms and assign teachers', 'add timetable slots', 'create exams, enter and publish marks',
        'create assignments and grade work', 'add and update admission leads', 'post announcements and calendar events, and notify people or send a WhatsApp message',
        'manage library books, lend and return them, and decide book requests', 'manage hostel rooms and beds', 'manage bus routes and stops and decide transport requests',
        'review leave and decide elective and student requests', 'update medical records', 'raise, reply to and update tickets', 'request extra seats',
      ],
      examples: ['Who is absent today?', 'Show all overdue invoices', 'How many students are enrolled in Class 6?'],
      notYet: ['quizzes', 'document requests and document types'],
    }),
    signInTopic(),
    { ...notificationsTopic, tips: [accessTip] },
  ],
};
