import type { RoleGuide } from './types';
import { askAgentTopic, notificationsTopic, accessTip, signInTopic } from './shared';

export const studentGuide: RoleGuide = {
  slug: 'student',
  hubTitle: 'Student Hub',
  hubDesc: 'Everything you need to get the most out of your student portal.',
  heroText: 'Find your classes, assignments, quizzes, attendance, exams and more, all in one place.',
  quickActions: ['assignments', 'quizzes', 'study-help', 'timetable', 'attendance', 'document-requests'],
  help: {
    title: 'Still need help?',
    text: 'Raise a request with the school and track its progress.',
    label: 'Raise a Ticket',
    href: '/student/tickets',
  },
  topics: [
    {
      id: 'dashboard', title: 'Dashboard Overview', category: 'Home Base', icon: '◳',
      href: '/student', openLabel: 'Open Dashboard',
      summary: 'Your daily starting point: a quick snapshot of what to focus on today.',
      highlights: [
        { label: 'Upcoming Classes', text: 'Today\'s remaining classes. Online classes show a Live button when available.' },
        { label: 'Quick Stats', text: 'Monthly attendance, pending assignments, upcoming exams and fees pending.' },
        { label: 'My Performance', text: 'How you are doing across subjects.' },
        { label: 'Recent Announcements', text: 'The latest updates from your school.' },
      ],
    },
    {
      id: 'subjects', title: 'Choose your electives', category: 'Academics', icon: '⊕',
      href: '/student/subjects', openLabel: 'Open Subject Registration',
      summary: 'Your core subjects are already on your timetable. Choose elective subjects here; a teacher approves each request.',
      steps: [
        'Browse "Electives for your class". Electives marked Full have no places left.',
        'Click Register on the electives you want. The request is sent for approval.',
        'While a request is pending you can Withdraw it; once approved (Registered) you can Drop the elective.',
        'Older decisions are listed under "Past requests". Approved electives appear on your timetable, quizzes and materials.',
      ],
    },
    {
      id: 'timetable', title: 'Never miss a class.', category: 'Academics', icon: '▥',
      href: '/student/timetable', openLabel: 'Open Timetable',
      summary: 'Your complete weekly class schedule.',
      steps: [
        'Switch between Day, Week and Month views.',
        'Move with ‹ Prev, Today and Next ›.',
        'Click a class to see the subject, teacher, time and room.',
      ],
    },
    {
      id: 'assignments', title: 'From assignment to submission.', category: 'Academics', icon: '✐',
      href: '/student/assignments', openLabel: 'Open Assignments',
      summary: 'See your homework and submit your work before the due date.',
      workflow: ['Open assignment', 'Read instructions', 'Attach your work', 'Submit', 'See your grade'],
      steps: [
        'Use the Upcoming and Past tabs, and search or filter by subject and status (Pending, Completed, Incomplete).',
        'Open "📎 Material" if your teacher attached a worksheet.',
        'Upload a file or paste a link, then click Submit.',
        'Until it is graded, use "View work" to check what you sent and Resubmit to replace it.',
        'Once graded, your teacher\'s feedback is shown next to the assignment.',
      ],
    },
    {
      id: 'quizzes', title: 'Take quizzes', category: 'Academics', icon: '☑', isNew: true,
      href: '/student/quizzes', openLabel: 'Open Quizzes',
      summary: 'Multiple-choice quizzes published by your teachers. Your result appears as soon as you submit.',
      workflow: ['Open quiz', 'Read instructions', 'Start', 'Answer', 'Submit', 'View result'],
      steps: [
        'Open a quiz from "Available Quizzes" to see the subject, teacher, number of questions, total marks and duration.',
        'Read the instructions and press Start. If the quiz is timed, the timer starts now.',
        'Answer each question. Use Previous/Next or the question numbers to move around, and change answers any time before submitting. The "answered" counter shows your progress.',
        'Submit. If any questions are unanswered you are asked to confirm first. You then immediately see your score and, for each question, your answer and whether it was correct.',
      ],
      tips: [
        'You have one attempt per quiz.',
        'A timed quiz submits itself automatically when time runs out.',
        'Finished quizzes move to Completed; reopen them with "View Result". All your scores are under "Previous Attempts".',
      ],
    },
    {
      id: 'performance', title: 'Track your progress.', category: 'Academics', icon: '◉',
      href: '/student/performance', openLabel: 'Open Performance',
      summary: 'Your results by academic year and term, and your report card.',
      highlights: [
        { label: 'Term by term', text: 'Subjects, marks, percentage and grade for each term.' },
        { label: 'Highlights', text: 'Attendance, total marks, best subject and the subject that needs support.' },
        { label: 'Report card', text: 'Download the school-issued report card as a PDF.' },
      ],
      steps: ['Pick an academic year.', 'Search results by subject or exam.'],
    },
    {
      id: 'attendance', title: 'Know where you stand.', category: 'Academics', icon: '☱',
      href: '/student/attendance', openLabel: 'Open Attendance',
      summary: 'Your attendance calendar, trend, subject-wise attendance and leave applications.',
      highlights: [
        { label: 'Calendar', text: 'Present, absent, leave and holidays day by day. Click a day to see the subjects scheduled.' },
        { label: 'Attendance Trend', text: 'How your attendance has moved month by month.' },
        { label: 'Subject-wise Attendance', text: 'Your attendance in each subject.' },
      ],
      tips: ['If your monthly attendance falls below 75%, you will see a warning.'],
    },
    {
      id: 'leave', title: 'Apply for leave', category: 'Academics', icon: '⛱',
      href: '/student/attendance', openLabel: 'Open Attendance',
      summary: 'Apply for leave from the Attendance page; your class teacher approves it.',
      steps: [
        'Open Attendance and click "Apply Leave" (or "+ Apply" under Leave Applications).',
        'Enter the From Date, To Date and Reason, then submit.',
        'Track the status (Pending, Approved, Rejected) and any note from your teacher under Leave Applications.',
      ],
      tips: ['Leave cannot be applied for dates in the past.'],
    },
    {
      id: 'material', title: 'Course material', category: 'Academics', icon: '❑',
      href: '/student/material', openLabel: 'Open Course Material',
      summary: 'Study materials shared by your teachers.',
      steps: ['Search by title or date.', 'Click Download / View to open a file or link.'],
    },
    {
      id: 'study-help', title: 'Study Help (Learning Buddy)', category: 'Academics', icon: '✦', isNew: true,
      href: '/student/study-help', openLabel: 'Open Study Help',
      summary: 'An AI study companion for your own subjects: explanations, worked examples, practice, quizzes and revision aids.',
      steps: [
        'Choose a subject (only the subjects you study are listed) and type a topic, e.g. fractions or photosynthesis.',
        'Say what you want help with.',
        'Pick a learning mode and click "Ask for help".',
      ],
      highlights: [
        { label: 'Explanation', text: 'The core idea, an example and why it works.' },
        { label: 'Worked example', text: 'One problem worked through step by step.' },
        { label: 'Practice', text: 'Questions one at a time, with hints.' },
        { label: 'Quiz', text: 'Multiple choice, scored as you go.' },
        { label: 'Flashcards', text: 'Recall, then flip.' },
        { label: 'Revision notes', text: 'Condensed notes and self-test prompts.' },
        { label: 'Mind map', text: 'The topic as an expandable tree.' },
        { label: 'Exam answer', text: 'Exam-style questions with model answers.' },
      ],
      tips: ['AI-written answers use AI credits. See AI Credits for your free monthly allowance.'],
    },
    {
      id: 'calendar', title: 'Calendar & events', category: 'School Life', icon: '▤',
      href: '/student/calendar', openLabel: 'Open Calendar & Events',
      summary: 'Upcoming holidays, exams and school events.',
    },
    {
      id: 'announcements', title: 'Stay in the loop.', category: 'School Life', icon: '◍',
      href: '/student/announcements', openLabel: 'Open Announcements',
      summary: 'Important updates from the school administration and your teachers.',
      steps: ['Open an announcement to read the full details and any attachment.', 'Recent announcements are also shown on your Dashboard.'],
    },
    {
      id: 'library', title: 'Your digital library desk.', category: 'School Life', icon: '▢',
      href: '/student/library', openLabel: 'Open Library',
      summary: 'Search the catalogue, request books, and track what is issued to you.',
      highlights: [
        { label: 'My checked-out books', text: 'Books issued to you with due dates and fines. Filter to see what is Due soon, Overdue or Returned.' },
        { label: 'Library catalogue', text: 'Search titles, authors, ISBNs, categories and publishers. Filter physical books or digital resources.' },
        { label: 'My requests', text: 'Track the librarian\'s decision on books you asked for. Approved books then appear in your checked-out list.' },
      ],
      tips: ['Request an available physical copy, or open a digital resource online straight away.'],
    },
    {
      id: 'notes', title: 'Library notes', category: 'School Life', icon: '✎',
      href: '/student/notes', openLabel: 'Open Library Notes',
      summary: 'Study notes filed by class, subject, academic year, exam and language.',
      steps: ['Filter by class, subject, year or exam.', 'Click Open to read a note or its attached file.'],
    },
    {
      id: 'question-papers', title: 'Question papers', category: 'School Life', icon: '❑',
      href: '/student/question-papers', openLabel: 'Open Question Papers',
      summary: 'Past question papers filed by class, subject, academic year, exam and language.',
      steps: ['Filter by class, subject, year or exam.', 'Click Open to view a paper.'],
    },
    {
      id: 'transport', title: 'Manage your commute.', category: 'School Life', icon: '⛒',
      href: '/student/transport', openLabel: 'Open Transport',
      summary: 'Your bus route, stop and driver contact, and requests for a place on a route.',
      steps: [
        'If you have a route, you will see the bus route, vehicle number, your stop and the driver\'s contact.',
        'To ask for a place, choose a route and stop and the direction (both ways, pick-up only or drop only), then click "Send request".',
        'Track it under "Your requests". You can Withdraw a request while it is awaiting a decision.',
      ],
      tips: ['Nothing is charged until the school office grants the place.'],
    },
    {
      id: 'documents', title: 'My documents', category: 'School Life', icon: '🗎',
      href: '/student/documents', openLabel: 'Open Documents',
      summary: 'Your ID card, report cards and personal letters issued by the school.',
      steps: ['Search by name, type or date.', 'Click "🪪 Student ID Card" to download your ID card.'],
    },
    {
      id: 'payments', title: 'Keep your fees on track.', category: 'Account', icon: '₹',
      href: '/student/payments', openLabel: 'Open Payments',
      summary: 'Your fee invoices, installments, payment history and receipts.',
      highlights: [
        { label: 'Summary', text: 'Total fees, paid, pending and overdue, with a fee breakdown and payment trend.' },
        { label: 'Invoices', text: 'Each invoice with its due date and status. Pay online, and open the timeline to see its history.' },
        { label: 'Downloads', text: 'Download the invoice PDF, and the receipt PDF once paid.' },
      ],
      steps: ['Pick the academic year.', 'Click "Pay ₹…" on an outstanding invoice and complete the payment.'],
    },
    {
      id: 'ai-credits', title: 'AI credits', category: 'Account', icon: '✦',
      href: '/student/ai-credits', openLabel: 'Open AI Credits',
      summary: 'Your free monthly allowance for AI-written answers, and how to add more.',
      highlights: [
        { label: 'Costs 1 credit', text: 'An AI-written explanation, practice set, flashcards, notes or mind map.' },
        { label: 'Always free', text: 'Questions about your attendance, fees, results, timetable and homework.' },
        { label: 'Also free', text: 'Anything the assistant refuses, and anything that fails on our side.' },
      ],
      steps: ['Check "Credits left" and "Free this month".', 'Click "Add credits" to buy a top-up. Past purchases are under "Top-up history".'],
    },
    {
      id: 'profile', title: 'My profile', category: 'Account', icon: '◉',
      href: '/student/profile', openLabel: 'Open My Profile',
      summary: 'Your school record, class, guardians and ID card, and requests to correct or add to your record.',
      steps: [
        'See your class, class teacher, class representative and guardians.',
        'Click "Request Edit" to ask for a profile correction: choose the fields, give a reason and optionally attach a supporting document. Your class teacher reviews it.',
        'Under "Co-curricular record", click "Request activity" to add an achievement (activity, category, level, date and details, with an optional certificate). Your class teacher verifies it.',
      ],
      tips: ['Your admission number, class and roll number are set by the school office and cannot be changed by request.'],
    },
    {
      id: 'document-requests', title: 'Request a certificate or letter', shortTitle: 'Request a Document', category: 'Account', icon: '⇄', isNew: true,
      href: '/student/profile', openLabel: 'Open My Profile',
      summary: 'Ask the school office for official documents such as a bonafide certificate, from the Document Requests section of My Profile.',
      workflow: ['Request', 'Pending', 'Under review', 'Approved', 'Ready', 'Download'],
      steps: [
        'Open My Profile and click "+ Request a document".',
        'Choose the document type, write the reason/purpose, answer any questions that type asks, and optionally add a "Required by" date and additional information.',
        'Track the status in the list. When it is Ready, click "Download Document".',
        'You can cancel a request while it is still open.',
      ],
      tips: [
        'If a request is rejected, the reason is shown so you know what to do next.',
        'You can have one open request per document type at a time.',
      ],
    },
    {
      id: 'tickets', title: 'Help & support', category: 'Account', icon: '✉',
      href: '/student/tickets', openLabel: 'Open Help & Support',
      summary: 'Raise a request with the school and track its progress.',
      steps: [
        'Click "+ New ticket", enter a subject and message, and optionally attach a file.',
        'Choose who it goes to under "Route to": class teacher, admin office, warden, librarian or principal.',
        'Raise the ticket and follow the replies and its status here.',
      ],
    },
    askAgentTopic({
      askAbout: [
        'your attendance', 'your timetable, classes and subjects', 'your results and report card', 'your homework',
        'fees and how to pay', 'announcements and the calendar', 'library books and your book requests',
        'your bus and transport requests', 'your leave, electives and profile requests', 'your tickets and documents',
      ],
      canDo: [
        'submit an assignment', 'request a library book or cancel the request', 'ask for a bus place or withdraw the request',
        'apply for leave', 'register for or withdraw from an elective', 'request a co-curricular activity or a profile correction (or cancel one)',
        'raise a ticket',
      ],
      examples: ['What is my attendance this month?', 'What homework is due this week?', 'Apply for leave tomorrow, I have a fever'],
      notYet: ['quizzes', 'document requests'],
    }),
    signInTopic(),
    { ...notificationsTopic, tips: [accessTip] },
  ],
};
