import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import PDFDocument from 'pdfkit';
import { Document } from '../models/document.model.js';
import { Profile } from '../models/profile.model.js';
import { Section, SubjectOffering } from '../models/academics.model.js';
import { env } from '../config/env.js';
import { logger } from '../utils/logger.js';

/**
 * Seeds course materials that can actually be opened.
 *
 * Document records used to be created ad-hoc during testing with placeholder
 * paths like `/uploads/test.pdf` — files nobody ever wrote. The record looked
 * fine in the database and the Documents tab listed it, but every view or
 * download 404'd, because the bytes never existed. (The Atlas theory in the
 * issue sheet was a red herring: the same records 404 against a purely local
 * database.)
 *
 * So this writes the PDF first and derives the record from what it actually
 * wrote. A document row here cannot reference a file that is not on disk.
 */

function writePdf(absPath, { title, lines }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(absPath);
    doc.pipe(stream);

    doc.fontSize(20).text(title, { underline: true });
    doc.moveDown();
    doc.fontSize(12);
    for (const line of lines) {
      doc.text(line);
      doc.moveDown(0.4);
    }
    doc.moveDown();
    doc.fontSize(9).fillColor('#666').text(`${env.SCHOOL_NAME} — sample course material generated by the seeder.`);
    doc.end();

    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

const MATERIALS = [
  {
    title: 'Algebra — Chapter 1 Notes',
    subject: 'Mathematics',
    lines: [
      'A linear equation in one variable takes the form ax + b = 0, where a ≠ 0.',
      'To solve: isolate the variable by performing the same operation on both sides.',
      'Worked example: 3x + 6 = 0  →  3x = -6  →  x = -2.',
      'Practice: solve 5x - 15 = 0, 2x + 7 = 19, and -4x + 8 = 0.',
    ],
  },
  {
    title: 'Photosynthesis — Revision Sheet',
    subject: 'Science',
    lines: [
      'Photosynthesis converts light energy into chemical energy stored as glucose.',
      'Overall equation: 6CO2 + 6H2O + light → C6H12O6 + 6O2.',
      'It happens in the chloroplasts, mostly in the palisade cells of the leaf.',
      'Limiting factors: light intensity, carbon dioxide concentration, temperature.',
    ],
  },
  {
    title: 'Essay Writing — Structure Guide',
    subject: 'English',
    lines: [
      'An essay has three parts: introduction, body, and conclusion.',
      'The introduction states your position in one clear sentence.',
      'Each body paragraph makes one point and supports it with evidence.',
      'The conclusion answers "so what?" — it does not simply repeat the introduction.',
    ],
  },
];

export async function seedDocuments({ force = false } = {}) {
  const existing = await Document.countDocuments({ type: 'CUSTOM' });
  if (existing > 0 && !force) {
    logger.info(`  -  ${existing} course material document(s) already present, skipping`);
    return { created: 0, skipped: existing };
  }

  const author = await Profile.findOne().sort({ createdAt: 1 });
  if (!author) {
    logger.warn('  ✘  No profile found to attribute documents to — run the main seed first');
    return { created: 0, skipped: 0 };
  }

  const uploadDir = path.resolve(process.cwd(), env.UPLOAD_DIR);
  fs.mkdirSync(uploadDir, { recursive: true });

  let created = 0;
  for (const material of MATERIALS) {
    const offering = await SubjectOffering.findOne().populate({
      path: 'subjectId',
      match: { name: material.subject },
    });
    const matched = offering?.subjectId ? offering : await SubjectOffering.findOne();
    const section = matched?.sectionId ? await Section.findById(matched.sectionId) : await Section.findOne();

    // The stored name matches the uploads convention (uuid-originalname) so
    // these behave exactly like a real upload.
    const filename = `${crypto.randomUUID()}-${material.title.replace(/[^a-z0-9]+/gi, '_')}.pdf`;
    const absPath = path.join(uploadDir, filename);
    await writePdf(absPath, { title: material.title, lines: material.lines });

    const bytes = fs.statSync(absPath).size;
    await Document.create({
      title: material.title,
      type: 'CUSTOM',
      fileUrl: `/${env.UPLOAD_DIR}/${filename}`,
      mimeType: 'application/pdf',
      visibleToRoles: ['STUDENT', 'PARENT', 'TEACHER', 'ADMIN', 'PRINCIPAL', 'OWNER'],
      authorProfileId: author._id,
      sectionId: section?._id ?? null,
      subjectOfferingId: matched?._id ?? null,
    });

    logger.info(`  ✔  ${material.title} → /${env.UPLOAD_DIR}/${filename} (${bytes} bytes)`);
    created++;
  }

  return { created, skipped: 0 };
}

/**
 * Reports document rows whose file is missing from local storage.
 *
 * Worth running after any restore or environment switch: a database copied
 * from a server references uploads that only exist on that server, and this is
 * what that looks like before users start reporting broken downloads.
 */
export async function auditDocumentFiles() {
  const docs = await Document.find().lean();
  const broken = [];
  for (const doc of docs) {
    const url = String(doc.fileUrl ?? '');
    if (/^https?:\/\//i.test(url)) continue; // external link, not ours to check
    const abs = path.resolve(process.cwd(), url.replace(/^\//, ''));
    if (!fs.existsSync(abs)) broken.push({ id: String(doc._id), title: doc.title, fileUrl: url });
  }
  return { total: docs.length, broken };
}

/**
 * Removes document rows that can no longer be served.
 *
 * Two kinds:
 *
 *   - Ad-hoc test rows: placeholder paths that were never written, and links to
 *     domains that are not ours. Indistinguishable from real course material in
 *     the UI until someone clicks one and gets a 404 (or leaves the site).
 *   - Orphans: rows whose section, offering or author no longer exists. A full
 *     re-seed drops those collections and rebuilds them with new ids, so
 *     documents created beforehand end up pointing at nothing. They are still
 *     *listed*, but the class-scoping filter excludes them from every student,
 *     so the Course Materials tab silently goes empty — which is exactly what
 *     happened the first time this seeder ran after seed:school.
 */
export async function pruneStaleDocuments() {
  const byUrl = await Document.find({
    $or: [
      { fileUrl: { $in: ['/uploads/test.pdf', '/uploads/x.pdf'] } },
      { fileUrl: /^https?:\/\/(?:www\.)?aravid\.com/i },
    ],
  }).lean();

  // Orphan check. Only rows that name a reference are candidates — a document
  // with no sectionId is school-wide, not broken.
  const orphans = [];
  for (const doc of await Document.find().lean()) {
    if (byUrl.some((d) => String(d._id) === String(doc._id))) continue;
    const [section, offering, author] = await Promise.all([
      doc.sectionId ? Section.exists({ _id: doc.sectionId }) : true,
      doc.subjectOfferingId ? SubjectOffering.exists({ _id: doc.subjectOfferingId }) : true,
      doc.authorProfileId ? Profile.exists({ _id: doc.authorProfileId }) : true,
    ]);
    if (!section || !offering || !author) {
      orphans.push({ ...doc, _why: !section ? 'section' : !offering ? 'offering' : 'author' });
    }
  }

  const stale = [...byUrl, ...orphans];
  if (stale.length === 0) return { removed: 0 };

  await Document.deleteMany({ _id: { $in: stale.map((d) => d._id) } });
  for (const d of byUrl) logger.info(`  ✔  removed stale document "${d.title}" → ${d.fileUrl}`);
  for (const d of orphans) logger.info(`  ✔  removed orphaned document "${d.title}" (its ${d._why} no longer exists)`);
  return { removed: stale.length };
}
